/**
 * Custom build script for Next.js.
 * - Disables worker threads to avoid race condition with pages-manifest.json.
 * - Uses single CPU to avoid race condition with static page generation.
 * - Creates pages-manifest.json if missing (Next.js 15.5+ turbopack production
 *   build doesn't generate it for App Router-only projects, but it's required
 *   during "Collecting page data" step).
 * - Removes Pages Router stubs (_error/_app/_document) that reference turbopack
 *   runtime (breaks esbuild in opennextjs-cloudflare).
 * - Handles Next.js 15 App Router /_error module bug gracefully.
 */
import { execSync } from "child_process";
import { existsSync, mkdirSync, writeFileSync, unlinkSync, readdirSync, copyFileSync, readFileSync } from "fs";
import { join } from "path";

const buildDir = join(process.cwd(), ".next");
const serverDir = join(buildDir, "server");

// Ensure .next/server exists (may be needed by Next.js during early build phase).
mkdirSync(serverDir, { recursive: true });
// NOTE: We do NOT pre-create pages-manifest.json here.
// Next.js 15.5+ turbopack generates _app/_document/_error stubs that reference
// [turbopack]_runtime.js which doesn't exist in production builds. If pages-manifest
// maps to these broken stubs, "Collecting page data" crashes.
// Instead, we create a minimal manifest AFTER the build (in the catch block or post-build).

try {
  execSync("npx next build", {
    stdio: "inherit",
    cwd: process.cwd(),
    env: {
      ...process.env,
      NEXT_PRIVATE_WORKER_THREADS: "false",
      NEXT_PRIVATE_CPUS: "1",
    },
  });
} catch (e) {
  // Check if the build output was actually generated despite the error.
  // Next.js 15 App Router throws "Cannot find module for page: /_error"
  // or turbopack runtime require errors after successful compilation —
  // these are safe to ignore when the core App Router output exists.
  const hasAppRoutes = existsSync(join(serverDir, "app"));
  const hasBuildManifest = existsSync(join(buildDir, "build-manifest.json"));
  if (hasAppRoutes && hasBuildManifest) {
    console.warn("\n⚠ Next.js build exited with error but app routes exist — continuing (likely Pages Router stub bug).\n");
  } else {
    throw e;
  }
}

// Create pages-manifest.json post-build (required by opennextjs-cloudflare).
// For App Router-only projects, an empty manifest is sufficient.
if (!existsSync(join(serverDir, "pages-manifest.json"))) {
  writeFileSync(join(serverDir, "pages-manifest.json"), "{}");
  console.log("  Created pages-manifest.json in server output.");
}

// Ensure pages-manifest.json exists in standalone output too.
// Create unconditionally — opennextjs-cloudflare creates the standalone dir AFTER
// our build script, but reads pages-manifest.json from it during bundling.
const standaloneNextDir = join(buildDir, "standalone", ".next");
const standaloneServerDir = join(standaloneNextDir, "server");
mkdirSync(standaloneServerDir, { recursive: true });
if (!existsSync(join(standaloneServerDir, "pages-manifest.json"))) {
  writeFileSync(join(standaloneServerDir, "pages-manifest.json"), "{}");
  console.log("  Created pages-manifest.json in standalone output.");
}

// Copy BUILD_ID to standalone output (required by opennextjs-cloudflare bundler).
// When the build exits with error (/_error module bug), the standalone output
// may be incomplete — ensure BUILD_ID is present.
const buildIdPath = join(buildDir, "BUILD_ID");
const standaloneBuildIdPath = join(standaloneNextDir, "BUILD_ID");
if (existsSync(buildIdPath) && !existsSync(standaloneBuildIdPath)) {
  copyFileSync(buildIdPath, standaloneBuildIdPath);
  console.log("  Copied BUILD_ID to standalone output.");
}

// Copy other critical manifests to standalone if missing
const criticalFiles = [
  "build-manifest.json",
  "prerender-manifest.json",
  "routes-manifest.json",
  "required-server-files.json",
];
for (const file of criticalFiles) {
  const src = join(buildDir, file);
  const dst = join(standaloneNextDir, file);
  if (existsSync(src) && !existsSync(dst)) {
    copyFileSync(src, dst);
    console.log(`  Copied ${file} to standalone output.`);
  }
}

// Remove Pages Router stubs that reference [turbopack]_runtime.js
// These are generated by Next.js 15.5+ but break esbuild in opennextjs-cloudflare
const pagesDir = join(serverDir, "pages");
if (existsSync(pagesDir)) {
  const stubs = ["_error.js", "_app.js", "_document.js"];
  for (const stub of stubs) {
    const stubPath = join(pagesDir, stub);
    if (existsSync(stubPath)) {
      try {
        unlinkSync(stubPath);
      } catch {}
    }
  }
  // Also clean standalone copy
  const standalonePagesDir = join(standaloneServerDir, "pages");
  if (existsSync(standalonePagesDir)) {
    for (const stub of stubs) {
      const stubPath = join(standalonePagesDir, stub);
      if (existsSync(stubPath)) {
        try {
          unlinkSync(stubPath);
        } catch {}
      }
    }
  }
  console.log("  Cleaned Pages Router stubs.");
}

// Fix App Router turbopack runtime references.
// Next.js 15.5+ intermittently generates turbopack-style page.js for certain dynamic routes
// even in webpack production builds. These break esbuild in opennextjs-cloudflare because
// esbuild can't resolve "[turbopack]_runtime.js" (brackets in path).
// Fix: create a stub runtime that esbuild can resolve, so the page can still load.
function findTurbopackRefs(dir) {
  if (!existsSync(dir)) return [];
  const found = [];
  const entries = readdirSync(dir, { withFileTypes: true });
  for (const entry of entries) {
    const fullPath = join(dir, entry.name);
    if (entry.isDirectory()) {
      found.push(...findTurbopackRefs(fullPath));
    } else if (entry.name.endsWith(".js")) {
      try {
        const content = readFileSync(fullPath, "utf8");
        if (content.includes("[turbopack]_runtime.js")) {
          found.push(fullPath);
        }
      } catch {}
    }
  }
  return found;
}
const appDir = join(serverDir, "app");
const turbopackFiles = findTurbopackRefs(appDir);
if (turbopackFiles.length > 0) {
  // Create a stub [turbopack]_runtime.js that esbuild can resolve.
  // The stub provides a minimal module loader compatible with turbopack's require pattern:
  //   var R = require("../chunks/ssr/[turbopack]_runtime.js")("module/path")
  //   R.c("chunk/path")
  const chunksDir = join(serverDir, "chunks", "ssr");
  mkdirSync(chunksDir, { recursive: true });
  const stubPath = join(chunksDir, "[turbopack]_runtime.js");
  if (!existsSync(stubPath)) {
    writeFileSync(stubPath, `
// Stub turbopack runtime for production builds.
// Provides minimal compatibility so pages that accidentally reference turbopack
// can still be bundled by esbuild and render at runtime.
module.exports = function turbopackRuntime(modulePath) {
  var loaded = {};
  return {
    c: function loadChunk(chunkPath) {
      if (!loaded[chunkPath]) {
        loaded[chunkPath] = true;
        try { require("../../" + chunkPath); } catch(e) {}
      }
    },
    m: {},
    i: function(id) { return this.m[id] || {}; }
  };
};
`.trim());
    console.log(`  Created [turbopack]_runtime.js stub (${turbopackFiles.length} file(s) reference it).`);
  }
}
